# This is the mods.toml file for Final Project Crystal Mod.

modLoader="javafml"               # mandatory
loaderVersion="[52,)"             # Forge 1.21.1 and above (52.x)

license="All Rights Reserved"

[[mods]]                          # mandatory
modId="finalprojectmod"           # MUST match MODID in your Java class
version="1.0.0"                   # whatever version you want
displayName="Final Project Crystal Mod"
authors="Andrew"
description='''
A simple crystal-themed mod for my final project.
Adds crystal ore, crystal blocks, and crystal shards
with a custom crystal creative tab.
'''

# --- Dependencies ---

[[dependencies.finalprojectmod]]
modId="forge"
mandatory=true
versionRange="[52,)"          # Forge 52.x (1.21.1+)
ordering="NONE"
side="BOTH"

[[dependencies.finalprojectmod]]
modId="minecraft"
mandatory=true
# Minimum 1.21.1, up to but not including 1.22
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"